[1keyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=1
KeyDownAction=[!SetOption 1Shape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption 1Label MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter 1Label][!UpdateMeter 1Shape][!Redraw]
KeyUpAction=[!SetOption 1Shape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption 1Label MeterStyle "Key#RGB#:S"][!UpdateMeter 1Label][!UpdateMeter 1Shape][!Redraw]
[2keyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=2
KeyDownAction=[!SetOption 2Shape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption 2Label MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter 2Label][!UpdateMeter 2Shape][!Redraw]
KeyUpAction=[!SetOption 2Shape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption 2Label MeterStyle "Key#RGB#:S"][!UpdateMeter 2Label][!UpdateMeter 2Shape][!Redraw]
[3keyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=3
KeyDownAction=[!SetOption 3Shape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption 3Label MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter 3Label][!UpdateMeter 3Shape][!Redraw]
KeyUpAction=[!SetOption 3Shape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption 3Label MeterStyle "Key#RGB#:S"][!UpdateMeter 3Label][!UpdateMeter 3Shape][!Redraw]
[4keyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=4
KeyDownAction=[!SetOption 4Shape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption 4Label MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter 4Label][!UpdateMeter 4Shape][!Redraw]
KeyUpAction=[!SetOption 4Shape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption 4Label MeterStyle "Key#RGB#:S"][!UpdateMeter 4Label][!UpdateMeter 4Shape][!Redraw]
[QkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=Q
KeyDownAction=[!SetOption QShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption QLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter QLabel][!UpdateMeter QShape][!Redraw]
KeyUpAction=[!SetOption QShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption QLabel MeterStyle "Key#RGB#:S"][!UpdateMeter QLabel][!UpdateMeter QShape][!Redraw]
[WkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=W
KeyDownAction=[!SetOption WShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption WLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter WLabel][!UpdateMeter WShape][!Redraw]
KeyUpAction=[!SetOption WShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption WLabel MeterStyle "Key#RGB#:S"][!UpdateMeter WLabel][!UpdateMeter WShape][!Redraw]
[EkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=E
KeyDownAction=[!SetOption EShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption ELabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter ELabel][!UpdateMeter EShape][!Redraw]
KeyUpAction=[!SetOption EShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption ELabel MeterStyle "Key#RGB#:S"][!UpdateMeter ELabel][!UpdateMeter EShape][!Redraw]
[RkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=R
KeyDownAction=[!SetOption RShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption RLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter RLabel][!UpdateMeter RShape][!Redraw]
KeyUpAction=[!SetOption RShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption RLabel MeterStyle "Key#RGB#:S"][!UpdateMeter RLabel][!UpdateMeter RShape][!Redraw]
[AkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=A
KeyDownAction=[!SetOption AShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption ALabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter ALabel][!UpdateMeter AShape][!Redraw]
KeyUpAction=[!SetOption AShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption ALabel MeterStyle "Key#RGB#:S"][!UpdateMeter ALabel][!UpdateMeter AShape][!Redraw]
[SkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=S
KeyDownAction=[!SetOption SShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption SLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter SLabel][!UpdateMeter SShape][!Redraw]
KeyUpAction=[!SetOption SShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption SLabel MeterStyle "Key#RGB#:S"][!UpdateMeter SLabel][!UpdateMeter SShape][!Redraw]
[DkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=D
KeyDownAction=[!SetOption DShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption DLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter DLabel][!UpdateMeter DShape][!Redraw]
KeyUpAction=[!SetOption DShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption DLabel MeterStyle "Key#RGB#:S"][!UpdateMeter DLabel][!UpdateMeter DShape][!Redraw]
[FkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=F
KeyDownAction=[!SetOption FShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption FLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter FLabel][!UpdateMeter FShape][!Redraw]
KeyUpAction=[!SetOption FShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption FLabel MeterStyle "Key#RGB#:S"][!UpdateMeter FLabel][!UpdateMeter FShape][!Redraw]
[GkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=G
KeyDownAction=[!SetOption GShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption GLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter GLabel][!UpdateMeter GShape][!Redraw]
KeyUpAction=[!SetOption GShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption GLabel MeterStyle "Key#RGB#:S"][!UpdateMeter GLabel][!UpdateMeter GShape][!Redraw]
[ZkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=Z
KeyDownAction=[!SetOption ZShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption ZLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter ZLabel][!UpdateMeter ZShape][!Redraw]
KeyUpAction=[!SetOption ZShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption ZLabel MeterStyle "Key#RGB#:S"][!UpdateMeter ZLabel][!UpdateMeter ZShape][!Redraw]
[XkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=X
KeyDownAction=[!SetOption XShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption XLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter XLabel][!UpdateMeter XShape][!Redraw]
KeyUpAction=[!SetOption XShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption XLabel MeterStyle "Key#RGB#:S"][!UpdateMeter XLabel][!UpdateMeter XShape][!Redraw]
[CkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=C
KeyDownAction=[!SetOption CShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption CLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter CLabel][!UpdateMeter CShape][!Redraw]
KeyUpAction=[!SetOption CShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption CLabel MeterStyle "Key#RGB#:S"][!UpdateMeter CLabel][!UpdateMeter CShape][!Redraw]
[VkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=V
KeyDownAction=[!SetOption VShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption VLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter VLabel][!UpdateMeter VShape][!Redraw]
KeyUpAction=[!SetOption VShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption VLabel MeterStyle "Key#RGB#:S"][!UpdateMeter VLabel][!UpdateMeter VShape][!Redraw]
