
[QkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=Q
KeyDownAction=[!SetOption QShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption QLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter QLabel][!UpdateMeter QShape][!Redraw]
KeyUpAction=[!SetOption QShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption QLabel MeterStyle "Key#RGB#:S"][!UpdateMeter QLabel][!UpdateMeter QShape][!Redraw]

[WkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=W
KeyDownAction=[!SetOption WShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption WLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter WLabel][!UpdateMeter WShape][!Redraw]
KeyUpAction=[!SetOption WShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption WLabel MeterStyle "Key#RGB#:S"][!UpdateMeter WLabel][!UpdateMeter WShape][!Redraw]

[EkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=E
KeyDownAction=[!SetOption EShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption ELabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter ELabel][!UpdateMeter EShape][!Redraw]
KeyUpAction=[!SetOption EShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption ELabel MeterStyle "Key#RGB#:S"][!UpdateMeter ELabel][!UpdateMeter EShape][!Redraw]

[RkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=R
KeyDownAction=[!SetOption RShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption RLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter RLabel][!UpdateMeter RShape][!Redraw]
KeyUpAction=[!SetOption RShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption RLabel MeterStyle "Key#RGB#:S"][!UpdateMeter RLabel][!UpdateMeter RShape][!Redraw]

[TkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=T
KeyDownAction=[!SetOption TShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption TLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter TLabel][!UpdateMeter TShape][!Redraw]
KeyUpAction=[!SetOption TShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption TLabel MeterStyle "Key#RGB#:S"][!UpdateMeter TLabel][!UpdateMeter TShape][!Redraw]

[YkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=Y
KeyDownAction=[!SetOption YShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption YLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter YLabel][!UpdateMeter YShape][!Redraw]
KeyUpAction=[!SetOption YShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption YLabel MeterStyle "Key#RGB#:S"][!UpdateMeter YLabel][!UpdateMeter YShape][!Redraw]

[UkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=U
KeyDownAction=[!SetOption UShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption ULabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter ULabel][!UpdateMeter UShape][!Redraw]
KeyUpAction=[!SetOption UShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption ULabel MeterStyle "Key#RGB#:S"][!UpdateMeter ULabel][!UpdateMeter UShape][!Redraw]

[IkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=I
KeyDownAction=[!SetOption IShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption ILabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter ILabel][!UpdateMeter IShape][!Redraw]
KeyUpAction=[!SetOption IShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption ILabel MeterStyle "Key#RGB#:S"][!UpdateMeter ILabel][!UpdateMeter IShape][!Redraw]

[OkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=O
KeyDownAction=[!SetOption OShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption OLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter OLabel][!UpdateMeter OShape][!Redraw]
KeyUpAction=[!SetOption OShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption OLabel MeterStyle "Key#RGB#:S"][!UpdateMeter OLabel][!UpdateMeter OShape][!Redraw]

[PkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=P
KeyDownAction=[!SetOption PShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption PLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter PLabel][!UpdateMeter PShape][!Redraw]
KeyUpAction=[!SetOption PShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption PLabel MeterStyle "Key#RGB#:S"][!UpdateMeter PLabel][!UpdateMeter PShape][!Redraw]

;===========================================================================================================================================================

[AkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=A
KeyDownAction=[!SetOption AShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption ALabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter ALabel][!UpdateMeter AShape][!Redraw]
KeyUpAction=[!SetOption AShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption ALabel MeterStyle "Key#RGB#:S"][!UpdateMeter ALabel][!UpdateMeter AShape][!Redraw]

[SkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=S
KeyDownAction=[!SetOption SShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption SLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter SLabel][!UpdateMeter SShape][!Redraw]
KeyUpAction=[!SetOption SShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption SLabel MeterStyle "Key#RGB#:S"][!UpdateMeter SLabel][!UpdateMeter SShape][!Redraw]

[DkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=D
KeyDownAction=[!SetOption DShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption DLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter DLabel][!UpdateMeter DShape][!Redraw]
KeyUpAction=[!SetOption DShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption DLabel MeterStyle "Key#RGB#:S"][!UpdateMeter DLabel][!UpdateMeter DShape][!Redraw]

[FkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=F
KeyDownAction=[!SetOption FShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption FLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter FLabel][!UpdateMeter FShape][!Redraw]
KeyUpAction=[!SetOption FShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption FLabel MeterStyle "Key#RGB#:S"][!UpdateMeter FLabel][!UpdateMeter FShape][!Redraw]

[GkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=G
KeyDownAction=[!SetOption GShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption GLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter GLabel][!UpdateMeter GShape][!Redraw]
KeyUpAction=[!SetOption GShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption GLabel MeterStyle "Key#RGB#:S"][!UpdateMeter GLabel][!UpdateMeter GShape][!Redraw]

[HkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=H
KeyDownAction=[!SetOption HShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption HLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter HLabel][!UpdateMeter HShape][!Redraw]
KeyUpAction=[!SetOption HShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption HLabel MeterStyle "Key#RGB#:S"][!UpdateMeter HLabel][!UpdateMeter HShape][!Redraw]

[JkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=J
KeyDownAction=[!SetOption JShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption JLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter JLabel][!UpdateMeter JShape][!Redraw]
KeyUpAction=[!SetOption JShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption JLabel MeterStyle "Key#RGB#:S"][!UpdateMeter JLabel][!UpdateMeter JShape][!Redraw]

[KkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=K
KeyDownAction=[!SetOption KShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption KLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter KLabel][!UpdateMeter KShape][!Redraw]
KeyUpAction=[!SetOption KShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption KLabel MeterStyle "Key#RGB#:S"][!UpdateMeter KLabel][!UpdateMeter KShape][!Redraw]

[LkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=L
KeyDownAction=[!SetOption LShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption LLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter LLabel][!UpdateMeter LShape][!Redraw]
KeyUpAction=[!SetOption LShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption LLabel MeterStyle "Key#RGB#:S"][!UpdateMeter LLabel][!UpdateMeter LShape][!Redraw]

;===========================================================================================================================================================

[ZkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=Z
KeyDownAction=[!SetOption ZShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption ZLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter ZLabel][!UpdateMeter ZShape][!Redraw]
KeyUpAction=[!SetOption ZShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption ZLabel MeterStyle "Key#RGB#:S"][!UpdateMeter ZLabel][!UpdateMeter ZShape][!Redraw]

[XkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=X
KeyDownAction=[!SetOption XShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption XLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter XLabel][!UpdateMeter XShape][!Redraw]
KeyUpAction=[!SetOption XShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption XLabel MeterStyle "Key#RGB#:S"][!UpdateMeter XLabel][!UpdateMeter XShape][!Redraw]

[CkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=C
KeyDownAction=[!SetOption CShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption CLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter CLabel][!UpdateMeter CShape][!Redraw]
KeyUpAction=[!SetOption CShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption CLabel MeterStyle "Key#RGB#:S"][!UpdateMeter CLabel][!UpdateMeter CShape][!Redraw]

[VkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=V
KeyDownAction=[!SetOption VShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption VLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter VLabel][!UpdateMeter VShape][!Redraw]
KeyUpAction=[!SetOption VShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption VLabel MeterStyle "Key#RGB#:S"][!UpdateMeter VLabel][!UpdateMeter VShape][!Redraw]

[BkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=B
KeyDownAction=[!SetOption BShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption BLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter BLabel][!UpdateMeter BShape][!Redraw]
KeyUpAction=[!SetOption BShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption BLabel MeterStyle "Key#RGB#:S"][!UpdateMeter BLabel][!UpdateMeter BShape][!Redraw]

[NkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=N
KeyDownAction=[!SetOption NShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption NLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter NLabel][!UpdateMeter NShape][!Redraw]
KeyUpAction=[!SetOption NShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption NLabel MeterStyle "Key#RGB#:S"][!UpdateMeter NLabel][!UpdateMeter NShape][!Redraw]

[MkeyMeasure]
Measure=Plugin
Plugin=HotKey
HotKey=M
KeyDownAction=[!SetOption MShape Fill "Fill Color #PressedColor#,#PressedOpacity#"][!SetOption NLabel MeterStyle "Key#RGBOverride#Over:S"][!UpdateMeter NLabel][!UpdateMeter MShape][!Redraw]
KeyUpAction=[!SetOption MShape Fill "Fill Color #DefaultColor#,#DefaultOpacity#"][!SetOption NLabel MeterStyle "Key#RGB#:S"][!UpdateMeter NLabel][!UpdateMeter MShape][!Redraw]
