;===========================================================================================================================================================

[Background]
Meter=Shape
Shape=Rectangle 0,0,(#Scale#*555+(#KeyPadding#-5)*11),(#Scale#*170),(#Corner#*5),(#Corner#*5) | StrokeWidth 0 | Fill Color #BackgroundColor#,#BackgroundOpacity#

;===========================================================================================================================================================

[QShape]
Meter=Shape
MeterStyle=KeyB:S
X=((50/2+#KeyPadding#)*#Scale#)
Y=((50/2+#KeyPadding#)*#Scale#)

[QLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=Q

[WShape]
Meter=Shape
MeterStyle=KeyB:S

[WLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=W

[EShape]
Meter=Shape
MeterStyle=KeyB:S

[ELabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=E

[RShape]
Meter=Shape
MeterStyle=KeyB:S

[RLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=R

[TShape]
Meter=Shape
MeterStyle=KeyB:S

[TLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=T

[YShape]
Meter=Shape
MeterStyle=KeyB:S

[YLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=Y

[UShape]
Meter=Shape
MeterStyle=KeyB:S

[ULabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=U

[IShape]
Meter=Shape
MeterStyle=KeyB:S

[ILabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=I

[OShape]
Meter=Shape
MeterStyle=KeyB:S

[OLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=O

[PShape]
Meter=Shape
MeterStyle=KeyB:S

[PLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=P

;===========================================================================================================================================================

[AShape]
Meter=Shape
MeterStyle=KeyB:S
X=((50+#KeyPadding#)*#Scale#)
Y=((50+#KeyPadding#)*#Scale#)r

[ALabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=A

[SShape]
Meter=Shape
MeterStyle=KeyB:S

[SLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=S

[DShape]
Meter=Shape
MeterStyle=KeyB:S

[DLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=D

[FShape]
Meter=Shape
MeterStyle=KeyB:S

[FLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=F

[GShape]
Meter=Shape
MeterStyle=KeyB:S

[GLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=G

[HShape]
Meter=Shape
MeterStyle=KeyB:S

[HLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=H

[JShape]
Meter=Shape
MeterStyle=KeyB:S

[JLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=J

[KShape]
Meter=Shape
MeterStyle=KeyB:S

[KLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=K

[LShape]
Meter=Shape
MeterStyle=KeyB:S

[LLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=L

;===========================================================================================================================================================

[ZShape]
Meter=Shape
MeterStyle=KeyB:S
X=((50*2+#KeyPadding#*2)*#Scale#)
Y=((50+#KeyPadding#)*#Scale#)r

[ZLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=Z

[ZShape]
Meter=Shape
MeterStyle=KeyB:S

[ZLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=Z

[XShape]
Meter=Shape
MeterStyle=KeyB:S

[XLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=X

[CShape]
Meter=Shape
MeterStyle=KeyB:S

[CLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=C

[VShape]
Meter=Shape
MeterStyle=KeyB:S

[VLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=V

[BShape]
Meter=Shape
MeterStyle=KeyB:S

[BLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=B

[NShape]
Meter=Shape
MeterStyle=KeyB:S

[NLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=N

[MShape]
Meter=Shape
MeterStyle=KeyB:S

[MLabel]
Meter=String
MeterStyle=Key#RGB#:S
Text=M
