[Variables]
Size=1
Corner=1
Blur=None
Font=Reef
Weight=400
BackgroundColor=0,0,0
BackgroundOpacity=0
DefaultOpacity=150
DefaultColor=0,0,0
DefaultFontColor=255,255,255
PressedOpacity=250
PressedColor=255,255,255
PressedFontColor=255,0,0

RGBSpeed=6

RGBOverride=[MeasureR],[MeasureG],[MeasureB]
RGB=0
RGBStatus=1
RGBHStatus=0
Update=20

MaxX=250
MaxY=250

KeyPadding=5

@includeHotkeys=#@#Actions\Hotkeys.ini
PressedOpacity=#PressedOpacity#
