[Variables]
; -------------------------------- Appearance -------------------------------- ;
Scale=1
Corner=1
Blur=None
Font=Reef
Weight=400
BackgroundColor=0,0,0
BackgroundOpacity=0
DefaultOpacity=200
DefaultColor=255,255,255
DefaultFontColor=255,255,255
PressedOpacity=200
PressedColor=0,0,0
PressedFontColor=255,0,0
KeyPadding=5
; ------------------------------------ RGB ----------------------------------- ;
RGBSpeed=5
RGB=1
RGBOverride=1
Rm.AniUpdate=40
; ---------------------------------- Circle ---------------------------------- ;
Circ=1
MaxX=250
MaxY=250
MouseFetchDelay=20
; ---------------------------------- Layout ---------------------------------- ;
Layout=WASD
; -------------------------------- Mouse & CPS ------------------------------- ;
Mouse=1
MouseCPS=0
; --------------------------------- Defaults --------------------------------- ;
PreviousX=0
PreviousY=0
NowX=0
NowY=0
CPS=LMB
CPS2=RMB
Clicks=0
Clicks2=0
P=40
R=10
GlobalP=10
