[Variables]
; -------------------------------- Appearance -------------------------------- ;
Scale=1
Corner=1
Blur=None
Font=Reef
Weight=400
BackgroundColor=0,0,0
BackgroundOpacity=0
DefaultOpacity=150
DefaultColor=0,0,0
DefaultFontColor=255,255,255
PressedOpacity=255
PressedColor=255,255,255
PressedFontColor=255,0,0
KeyPadding=5
; ------------------------------------ RGB ----------------------------------- ;
RGBSpeed=1
RGB=1
RGBOverride=1
Rm.AniUpdate=40
; ---------------------------------- Circle ---------------------------------- ;
Circ=0
MaxX=250
MaxY=250
MouseFetchDelay=20
; ---------------------------------- Layout ---------------------------------- ;
Layout=QWERTY
; -------------------------------- Mouse & CPS ------------------------------- ;
Mouse=0
MouseCPS=0
; --------------------------------- Defaults --------------------------------- ;
PreviousX=0
PreviousY=0
NowX=0
NowY=0
CPS=LMB
CPS2=RMB
Clicks=0
Clicks2=0
P=40
R=10
GlobalP=10
; --------------------------------- Fullboard -------------------------------- ;
Row1=1111000000
Row2=1111000000
Row3=111110000
Row4=0000000
